baseURL: ""
languageCode: en-us
defaultContentLanguage: en
title: GoodbyePlanet blog
theme: cupper-hugo-theme

params:
  footer: "**GoodbyePlanet blog** is created by [GoodbyePlanet](https://github.com/GoodbyePlanet). All rights to the **Mother Earth**."
  search: false

taxonomies:
  tag: tags
  author: authors

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: RSS
      url: /index.xml
      weight: 4
